name: Steps Examples

on: push

jobs:
  jobx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configuração do Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Verificação da Versão do Node.js
        run: node --version
